import { open } from './lib.mjs';
import assert from 'node:assert/strict';
const URL = 'http://localhost:5199/';
let n = 0;
const ok = m => console.log(`ok ${++n} ${m}`);

const { browser, page, errors } = await open();
await page.goto(URL);
await page.waitForSelector('#app:not([hidden])');
await page.clock.runFor(1000);
assert.equal(await page.locator('#tour').isVisible(), true); ok('tutorial aparece al estrenar');
assert.equal(await page.locator('#tourTitle').textContent(), 'Tu día, a tu manera');
await page.click('#tourNext'); await page.click('#tourNext');
assert.equal(await page.locator('#tourNext').textContent(), 'Empezar');
assert.equal(await page.locator('#tourSkip').isHidden(), true);
await page.click('#tourNext');
assert.equal(await page.locator('#tour').isHidden(), true); ok('tutorial se completa y se cierra');
await page.reload(); await page.waitForSelector('#app:not([hidden])'); await page.clock.runFor(2000);
assert.equal(await page.locator('#tour').isHidden(), true); ok('no vuelve a salir');
await page.click('#openMenu');
assert.equal(await page.locator('#sheetMenu.open').count(), 1);
await page.click('#menuTour'); assert.equal(await page.locator('#tour').isVisible(), true);
await page.click('#tourSkip'); ok('Ver tutorial desde el menú');
await page.click('#openMenu'); await page.click('#menuPomo');
assert.equal(await page.locator('#pomoTime').textContent(), '25:00');
assert.equal(await page.locator('#pomoToggle').textContent(), 'Empezar');
await page.click('#pomoToggle');
await page.clock.runFor(61000);
assert.match(await page.locator('#pomoTime').textContent(), /^(24:00|23:59)$/); ok('cuenta atrás');
await page.click('#closePomo');
assert.equal(await page.locator('#pomoPill').isVisible(), true);
assert.match(await page.locator('#pomoPill').textContent(), /^2[34]:\d\d$/); ok('píldora visible con el Pomodoro cerrado');
await page.click('#pomoPill');
await page.click('#pomoToggle');
assert.equal(await page.locator('#pomoToggle').textContent(), 'Seguir');
const t1 = await page.locator('#pomoTime').textContent();
await page.clock.runFor(5000);
assert.equal(await page.locator('#pomoTime').textContent(), t1); ok('pausa congela');
await page.click('#pomoReset');
await page.selectOption('#pomoFocus', '15');
assert.equal(await page.locator('#pomoTime').textContent(), '15:00'); ok('ajuste y reiniciar');
await page.click('#pomoToggle');
await page.click('#closePomo');
await page.clock.runFor(15 * 60000 + 2000);
assert.match(await page.locator('#toastMsg').textContent(), /descansar/);
assert.equal(await page.locator('#pomoPhase').textContent(), 'Descanso corto');
assert.equal(await page.locator('#pomoToggle').textContent(), 'Empezar');
assert.match(await page.locator('#pomoToday').textContent(), /completados hoy: 1/); ok('fin de fase: aviso, descanso y contador');
await page.click('#openMenu'); await page.click('#menuPomo'); await page.screenshot({ path: '/tmp/work/pomo.png' });
await page.reload(); await page.waitForSelector('#app:not([hidden])');
await page.click('#openMenu'); await page.click('#menuPomo');
assert.match(await page.locator('#pomoToday').textContent(), /completados hoy: 1/); ok('persiste tras recargar');
await page.click('#closePomo');
await page.click('#openStats');
assert.equal(await page.locator('#shareRow').isHidden(), true); ok('compartir oculto por defecto');
await page.click('#closeStats');
await page.click('#openSettings');
assert.equal(await page.getAttribute('#shareSwitch', 'aria-checked'), 'false');
await page.click('#shareSwitch');
assert.equal(await page.getAttribute('#shareSwitch', 'aria-checked'), 'true');
await page.click('#closeSettings');
await page.click('#openStats');
assert.equal(await page.locator('#shareRow').isVisible(), true);
await page.evaluate(() => { window.__shared = null; navigator.share = async d => { window.__shared = d; }; });
await page.click('#shareStats');
const shared = await page.evaluate(() => window.__shared);
assert.match(shared.text, /^Mi semana \(/); assert.doesNotMatch(shared.text, /undefined/); ok('compartir envía el texto');
await page.screenshot({ path: '/tmp/work/stats.png' });
await page.click('#statsTabMonth');
assert.equal(await page.locator('#shareRow').isHidden(), true); ok('no en vista mensual');
assert.deepEqual(errors, []);
await browser.close();
console.log('TODO OK');
