/**
 * lang-en.js — Diccionario español → inglés. La clave es el texto en español tal como aparece en el código.
 * Los huecos {0}, {1}… se rellenan con valores ya listos (números, fechas, nombres del usuario…).
 */
export const EN = Object.freeze({
  /* ── Pantalla principal y hojas (index.html) ── */
  'Ordenar': 'Sort', 'Más': 'More', 'Añadir': 'Add', 'Vaciar este día': 'Clear this day', 'Conectando…': 'Connecting…',
  'Correo': 'Email', 'Contraseña': 'Password', 'Entrar': 'Sign in', 'Crear cuenta': 'Create account',
  '¿Olvidaste la contraseña?': 'Forgot your password?', 'Al crear una cuenta aceptas los': 'By creating an account you accept the',
  'términos de uso': 'terms of use', 'y la': 'and the', 'política de privacidad': 'privacy policy', 'Reintentar': 'Try again',
  'Saltar': 'Skip', 'Siguiente': 'Next', 'Editar actividad': 'Edit activity', 'Nueva actividad': 'New activity',
  'Actividad': 'Activity', 'Inicio': 'Start', 'Fin': 'End', 'Subtareas': 'Subtasks', 'Lo que hice': 'What I did',
  'Repetir cada semana': 'Repeat every week', 'Dejar de repetir': 'Stop repeating', 'Guardar': 'Save', 'Cancelar': 'Cancel',
  'Eliminar': 'Delete', 'Este día': 'This day', 'Copiar a otros días': 'Copy to other days',
  'Repite este día en otros de esta semana o de la siguiente.': 'Repeat this day on others this week or next week.',
  'Plantillas': 'Templates', 'Guarda este día como plantilla o añade una de las tuyas.': 'Save this day as a template or add one of yours.',
  'Repeticiones': 'Repeats', 'Actividades que se crean solas cada semana.': 'Activities that are created automatically every week.',
  'Marcar como día de descanso': 'Mark as rest day', 'No suma ni rompe tu racha.': "Doesn't add to or break your streak.",
  'Cerrar': 'Close', 'Copiar día': 'Copy day', 'Reemplazar lo que ya hay': 'Replace what is already there',
  'Si está desactivado, solo se añaden las actividades que no chocan con las existentes.': 'If off, only activities that do not clash with existing ones are added.',
  'Copiar': 'Copy', 'Guardar este día como plantilla': 'Save this day as a template', 'Nombre': 'Name',
  'Guardar plantilla': 'Save template', 'Mis plantillas': 'My templates', 'Hecho': 'Done',
  'Actividades que se crean solas cada semana. Para crear una, activa «Repetir cada semana» al añadir una actividad.': 'Activities that are created automatically every week. To create one, turn on “Repeat every week” when adding an activity.',
  'Categorías': 'Categories', 'Elige el nombre y el color que quieras. Se aplican en toda la app y se sincronizan con tu cuenta.': 'Choose any name and colour. They apply across the app and sync with your account.',
  'Restaurar originales': 'Restore originals', 'Eliminar cuenta': 'Delete account',
  'Se borrarán para siempre tu cuenta y todos tus datos en la nube: horarios, plantillas, repeticiones, insignias y ajustes. También se vaciará este dispositivo. No se puede deshacer.': 'Your account and all your cloud data will be deleted for good: schedules, templates, repeats, badges and settings. This device will also be cleared. This cannot be undone.',
  'Si quieres conservar algo, cancela y usa antes «Exportar» en la copia de seguridad.': 'If you want to keep anything, cancel and use “Export” under Backup first.',
  'Escribe tu contraseña para confirmar': 'Enter your password to confirm', 'Eliminar para siempre': 'Delete forever',
  'Menú': 'Menu', 'Temporizador para concentrarte por tramos, con descansos.': 'A timer to focus in stretches, with breaks.',
  'Insignias': 'Badges', 'Tus logros y lo que te falta para el siguiente.': 'Your achievements and what is left for the next one.',
  'Ver tutorial': 'View tutorial', 'Repasa en 3 pantallas cómo funciona la app.': 'Go over how the app works in 3 screens.',
  'Empezar': 'Start', 'Reiniciar': 'Reset', 'Seguir': 'Resume', 'Pausar': 'Pause', 'Ajustes': 'Settings',
  'Concentración': 'Focus', 'Descanso corto': 'Short break', 'Descanso largo': 'Long break', 'Rondas hasta el largo': 'Rounds until the long break',
  'Avisos de actividad': 'Activity alerts', 'Avisar con antelación': 'Alert in advance', 'Meta diaria de la racha': 'Daily streak goal',
  'Días que cuentan para la racha': 'Days that count towards the streak', 'Aspecto': 'Appearance', 'Solo de este dispositivo.': 'This device only.',
  'Cambia el nombre y el color de cada categoría.': 'Change the name and colour of each category.', 'Editar': 'Edit',
  'Compartir resumen semanal': 'Share weekly summary', 'Estadísticas de uso': 'Usage statistics', 'Cuenta': 'Account',
  'Conectando con la nube…': 'Connecting to the cloud…', 'Cerrar sesión': 'Sign out', 'Copia de seguridad': 'Backup',
  'Guarda tus horarios y anotaciones en un archivo .json o restáuralos desde uno.': 'Save your schedules and notes to a .json file or restore them from one.',
  'Exportar': 'Export', 'Importar': 'Import', 'Instalar la app': 'Install the app', 'Instalar': 'Install',
  'Política de privacidad': 'Privacy policy', 'Términos de uso': 'Terms of use', 'Idioma': 'Language',
  'Cambia el idioma de la app. Tus actividades no se traducen.': 'Change the app language. Your activities are not translated.',
  'Esta semana': 'This week', 'Semana': 'Week', 'Mes': 'Month', 'Compartir resumen': 'Share summary',
  'Cuenta como hecho lo que marcas con el círculo de cada actividad.': 'Whatever you tick with each activity’s circle counts as done.',
  'Abrir el Pomodoro': 'Open the Pomodoro', 'Estadísticas de la semana': 'Weekly statistics', 'Días de la semana': 'Days of the week',
  'Racha': 'Streak', 'Tipo de actividad': 'Activity type', 'Añadir subtarea': 'Add subtask', 'Nueva subtarea': 'New subtask',
  'Anota aquí lo que hiciste': 'Write what you did here', 'Por ejemplo: Día de estudio': 'For example: Study day',
  'Minutos de concentración': 'Focus minutes', 'Minutos de descanso corto': 'Short break minutes', 'Minutos de descanso largo': 'Long break minutes',
  'Rondas hasta el descanso largo': 'Rounds until the long break', 'Antelación del aviso': 'Alert lead time', 'Tema': 'Theme',
  'Color de acento': 'Accent colour', 'Periodo': 'Period', 'Menú principal': 'Main menu', 'Arrastrar para mover': 'Drag to move',
  'Marcar como hecha': 'Mark as done', 'Progreso de la actividad': 'Activity progress', 'Actividades de hoy completadas': 'Today’s completed activities',
  'Semana anterior': 'Previous week', 'Semana siguiente': 'Next week', 'Mes anterior': 'Previous month', 'Mes siguiente': 'Next month', 'Hoy': 'Today',
  'Esta semana ': 'This week ', 'Abrir': 'Open', 'Ver': 'View', 'Deshacer': 'Undo',

  /* ── Tutorial ── */
  'Tu día, a tu manera': 'Your day, your way',
  'Toca «Añadir» para crear actividades con su hora. Marca el círculo cuando las hagas y desliza una fila para editarla o borrarla.': 'Tap “Add” to create activities with a time. Tick the circle when you do them and swipe a row to edit or delete it.',
  'Constancia sin agobios': 'Consistency without stress',
  'Cumple tu meta del día para mantener la racha. Puedes marcar días de descanso, ajustar la meta en Ajustes y ganar insignias por el camino.': 'Hit your daily goal to keep your streak. You can mark rest days, adjust the goal in Settings and earn badges along the way.',
  'Más herramientas': 'More tools',
  'En el menú ☰ tienes el Pomodoro para concentrarte por tramos. Con «Más» copias días, guardas plantillas y creas repeticiones semanales.': 'The ☰ menu has the Pomodoro to focus in stretches. With “More” you copy days, save templates and create weekly repeats.',

  /* ── Pomodoro ── */
  'Ronda {0} de {1}': 'Round {0} of {1}', 'Hoy aún no has completado ningún pomodoro.': 'You have not completed any pomodoro today yet.',
  'Pomodoros completados hoy: {0}': 'Pomodoros completed today: {0}', 'Pomodoro: {0}, {1}. Abrir': 'Pomodoro: {0}, {1}. Open',
  '¡Tiempo de descansar!': 'Time for a break!', '¡A concentrarse otra vez!': 'Time to focus again!',
  'Has terminado un pomodoro.': 'You have finished a pomodoro.', 'El descanso ha terminado.': 'The break is over.',
  'Toca {0}.': 'Next up: {0}.', 'Pulsa «Empezar» cuando estés listo.': 'Press “Start” when you are ready.',
  'descanso corto': 'short break', 'descanso largo': 'long break', 'concentración': 'focus',

  /* ── Categorías, aspecto, insignias, presets (config.js) ── */
  'Clase': 'Class', 'Gimnasio': 'Gym', 'Estudio': 'Study', 'Inglés': 'English', 'Libre': 'Free', 'Rutina': 'Routine',
  'Automático': 'Automatic', 'Claro': 'Light', 'Oscuro': 'Dark',
  'Verde': 'Green', 'Azul': 'Blue', 'Violeta': 'Violet', 'Ámbar': 'Amber', 'Rosa': 'Pink', 'Grafito': 'Graphite',
  'Domingo': 'Sunday', 'Lunes': 'Monday', 'Martes': 'Tuesday', 'Miércoles': 'Wednesday', 'Jueves': 'Thursday', 'Viernes': 'Friday', 'Sábado': 'Saturday',
  'Primer paso': 'First step', 'Completa tu primera actividad.': 'Complete your first activity.', 'En marcha': 'Up and running',
  'Completa 25 actividades.': 'Complete 25 activities.', 'Cien hechas': 'A hundred done', 'Completa 100 actividades.': 'Complete 100 activities.',
  'Imparable': 'Unstoppable', 'Completa 500 actividades.': 'Complete 500 activities.', 'Tres seguidos': 'Three in a row',
  'Racha de 3 días.': 'A 3-day streak.', 'Semana de fuego': 'Week on fire', 'Racha de 7 días.': 'A 7-day streak.',
  'Dos semanas': 'Two weeks', 'Racha de 14 días.': 'A 14-day streak.', 'Mes de hierro': 'Iron month', 'Racha de 30 días.': 'A 30-day streak.',
  'Centenario': 'Centenary', 'Racha de 100 días.': 'A 100-day streak.', 'Buen ritmo': 'Good pace', 'Cumple el objetivo en 10 días.': 'Hit your goal on 10 days.',
  'Medio centenar': 'Half a hundred', 'Cumple el objetivo en 50 días.': 'Hit your goal on 50 days.', 'Semana perfecta': 'Perfect week',
  'Cumple el objetivo todos los días con actividades de una semana (mínimo 3 días).': 'Hit your goal on every day with activities in a week (at least 3 days).',
  'Despertar y desayuno': 'Wake up and breakfast', 'Ducha y cuidado personal': 'Shower and personal care', 'Repasar el plan del día': 'Review the day’s plan',
  'Bloque de enfoque 1': 'Focus block 1', 'Descanso': 'Break', 'Bloque de enfoque 2': 'Focus block 2', 'Comida y descanso': 'Lunch and rest',
  'Bloque de enfoque 3': 'Focus block 3', 'Cerrar el día y planificar mañana': 'Wrap up the day and plan tomorrow',
  'Rutina de mañana': 'Morning routine', 'Añadir rutina de mañana': 'Add morning routine',
  'Jornada de estudio/trabajo': 'Study/work day', 'Añadir jornada de estudio/trabajo': 'Add study/work day',

  /* ── Interfaz dinámica (ui-components.js) ── */
  'Semana pasada': 'Last week', 'Próxima semana': 'Next week', 'Hace {0} semanas': '{0} weeks ago', 'Dentro de {0} semanas': 'In {0} weeks',
  'Próxima actividad: {0} a las {1}.': 'Next activity: {0} at {1}.', 'Bienvenido a Mi horario': 'Welcome to Mi horario',
  'Crea tu primer día con un toque.': 'Create your first day with one tap.', 'Tu día está en blanco': 'Your day is blank',
  'Elige un punto de partida y ajústalo a tu gusto.': 'Pick a starting point and adjust it to your liking.',
  '{0} – {1}, quedan {2}': '{0} – {1}, {2} left', 'Después: {0} a las {1}.': 'After that: {0} at {1}.',
  'Es la última actividad de hoy.': 'It is the last activity today.', 'Ahora no hay nada programado': 'Nothing is scheduled right now',
  'Faltan {0} para las {1}': '{0} until {1}', 'Siguiente: {0}.': 'Next: {0}.', '{0} empiezas a las {1}.': 'On {0} you start at {1}.', 'Mañana empiezas a las {0}.': 'Tomorrow you start at {0}.',
  'Mañana': 'Tomorrow', 'Día completado': 'Day complete', 'Descansa, ya no queda nada por hacer.': 'Rest up, there is nothing left to do.',
  'Sin actividades. Elige un punto de partida más abajo.': 'No activities. Pick a starting point below.', 'Volver a hoy': 'Back to today',
  'objetivo cumplido': 'goal met', 'objetivo no cumplido': 'goal not met', 'en curso': 'in progress', 'sin actividades': 'no activities',
  'por llegar': 'upcoming', 'día de descanso': 'rest day', 'no cuenta para la racha': 'does not count towards the streak',
  ' Tu racha de {0} sigue en pie.': ' Your {0} streak is still going.', 'Hoy es tu día de descanso.{0}': 'Today is your rest day.{0}',
  'Hoy es tu día de descanso.': 'Today is your rest day.',
  'Hoy no cuenta para tu racha, según tus ajustes.{0}': 'Today does not count towards your streak, according to your settings.{0}',
  'Hoy no tienes actividades.{0}': 'You have no activities today.{0}',
  'Planifica tu día y completa el {0} % de las actividades para empezar una racha.': 'Plan your day and complete {0} % of the activities to start a streak.',
  'Objetivo de hoy cumplido: {0} de {1}.': 'Today’s goal met: {0} of {1}.', 'llegar a {0} de racha': 'reach a streak of {0}', 'empezar tu racha': 'start your streak',
  'Hoy llevas {0} de {1}. Completa {2} para {3}.': 'Today you have {0} of {1}. Complete {2} to {3}.',
  'día de racha': 'day streak', 'días de racha': 'day streak', 'Esta semana…': 'This week…',
  'Mejor racha: {0}': 'Best streak: {0}', '{0} de {1} conseguidas': '{0} of {1} earned', 'Conseguida el {0}': 'Earned on {0}',
  '{0} de {1}': '{0} of {1}', 'Empieza con un punto de partida': 'Start with a starting point', 'Elige un punto de partida': 'Pick a starting point',
  'Un toque añade las actividades. Después puedes cambiar horas y nombres, o crear las tuyas con Añadir.': 'One tap adds the activities. Afterwards you can change times and names, or create your own with Add.',
  'Añadir rápido': 'Quick add', 'Cada semana': 'Every week', '{0}/{1} subtareas': '{0}/{1} subtasks',
  'Toca para anotar lo que hiciste': 'Tap to note what you did', 'hasta las {0}, {1}': 'until {0}, {1}', ' (día de origen)': ' (source day)',
  'Aún no tienes plantillas. Organiza un día a tu gusto y guárdalo para reutilizarlo con un toque.': 'You have no templates yet. Arrange a day the way you like and save it to reuse with one tap.',
  'No tienes actividades que se repitan. Al crear o editar una actividad, activa «Repetir cada semana».': 'You have no repeating activities. When creating or editing an activity, turn on “Repeat every week”.',
  'Marcar «{0}»': 'Mark “{0}”', 'Quitar «{0}»': 'Remove “{0}”', 'Eliminar {0}': 'Delete {0}', 'Dejar de repetir {0}': 'Stop repeating {0}',
  'Sin actividades esta semana.': 'No activities this week.', 'Sin actividades este mes.': 'No activities this month.',
  'hechas de {0} planificadas': 'done of {0} planned', 'Este mes': 'This month', 'Color de {0}': 'Colour of {0}',
  '{0} de {1} cumplieron la meta.': '{0} of {1} met the goal.',
  'Lunes a viernes': 'Monday to Friday', 'Todos los días': 'Every day', 'Fines de semana': 'Weekends',

  /* ── Mensajes de la app (app.js) ── */
  'Arrastra el icono de la derecha para mover una actividad. Las horas se recalculan manteniendo la duración de cada una.': 'Drag the icon on the right to move an activity. Times are recalculated keeping each one’s duration.',
  'Toca una actividad para editarla o anotar lo que hiciste. Desliza a la izquierda para eliminarla.': 'Tap an activity to edit it or note what you did. Swipe left to delete it.',
  'Actividad eliminada': 'Activity deleted', ' ({0} omitidas por solaparse)': ' ({0} skipped because they overlap)',
  ' Insignia nueva: {0}.': ' New badge: {0}.', ' {0} insignias nuevas.': ' {0} new badges.',
  '¡Objetivo de hoy cumplido! Racha: {0}.{1}': 'Today’s goal met! Streak: {0}.{1}', '¡Insignia conseguida!{0}': 'Badge earned!{0}',
  '¡Insignia conseguida: {0}!': 'Badge earned: {0}!', '¡{0} insignias conseguidas!': '{0} badges earned!',
  'Día vaciado': 'Day cleared', 'aplicar a las próximas semanas': 'apply to the coming weeks', 'Guardar igualmente': 'Save anyway',
  'Aplicar a las próximas semanas': 'Apply to the coming weeks', 'Se solapa con {0}.': 'Overlaps with {0}.', ' y ': ' and ', ' y {0} más': ' and {0} more', 'insignias nuevas': 'new badges',
  'Se repite cada semana ({0}). Por defecto, los cambios afectan solo a este día.': 'Repeats every week ({0}). By default, changes affect only this day.',
  'Se creará sola en los días que elijas, también en las semanas siguientes.': 'It will be created automatically on the days you choose, in the following weeks too.',
  'La repetición ya no existe.': 'That repeat no longer exists.', 'Ya no se repetirá después de este día.': 'It will no longer repeat after this day.',
  'Ya no se repetirá desde hoy.': 'It will no longer repeat from today.', 'Cambio aplicado a las próximas semanas.': 'Change applied to the coming weeks.',
  'Se repetirá cada semana ({0}).': 'It will repeat every week ({0}).', 'Este día no tiene actividades que copiar.': 'This day has no activities to copy.',
  'Semana mostrada: {0}': 'Week shown: {0}', 'Semana siguiente: {0}': 'Next week: {0}',
  'Se copiarán las {0} de {1}, sin marcar y sin anotaciones.': 'The {0} from {1} will be copied, unticked and without notes.',
  'Quitar día de descanso': 'Remove rest day', 'Solo se puede en hoy y en días que aún no han llegado.': 'Only possible for today and days that have not arrived yet.',
  'Volverá a contar para tu racha.': 'It will count towards your streak again.', 'Día de descanso marcado. No suma ni rompe tu racha.': 'Rest day marked. It neither adds to nor breaks your streak.',
  'Este día vuelve a contar para tu racha.': 'This day counts towards your streak again.',
  'Se borrará lo que haya en los días elegidos. Podrás deshacerlo justo después.': 'Whatever is on the chosen days will be erased. You can undo it right afterwards.',
  ' ({0} por solaparse)': ' ({0} because of overlaps)', 'Copiado a {0}{1}': 'Copied to {0}{1}',
  'Se guardarán las {0} de este día (sin anotaciones).': 'The {0} of this day will be saved (without notes).',
  'Este día está vacío: añade actividades para poder guardarlo como plantilla.': 'This day is empty: add activities to be able to save it as a template.',
  'Plantilla guardada': 'Template saved', 'Plantilla eliminada': 'Template deleted',
  'Resumen copiado. Pégalo donde quieras.': 'Summary copied. Paste it wherever you like.', 'No se pudo compartir el resumen.': 'The summary could not be shared.',
  'Ya están los nombres y colores originales.': 'The original names and colours are already in place.', 'Categorías restauradas': 'Categories restored',
  'En iPhone, añade primero la app a la pantalla de inicio (iOS 16.4 o superior).': 'On iPhone, first add the app to the home screen (iOS 16.4 or later).',
  'Este navegador no admite avisos.': 'This browser does not support alerts.', 'Bloqueados. Actívalos en los ajustes del sistema para esta app.': 'Blocked. Turn them on in the system settings for this app.',
  'Te aviso cuando empiece cada actividad, incluso con la app cerrada.': 'I will alert you when each activity starts, even with the app closed.',
  'Te aviso cuando empiece cada actividad, con la app abierta o en segundo plano.': 'I will alert you when each activity starts, with the app open or in the background.',
  'Recibe un aviso justo cuando empiece cada actividad.': 'Get an alert right when each activity starts.',
  'No disponible en este dispositivo o bloqueado por el navegador.': 'Not available on this device or blocked by the browser.',
  'Envía datos anónimos de uso a Google Analytics, nunca tus actividades ni tus notas.': 'Sends anonymous usage data to Google Analytics, never your activities or notes.',
  'Te aviso justo cuando empieza cada actividad.': 'I alert you right when each activity starts.',
  'Te aviso {0} min antes de que empiece cada actividad.': 'I alert you {0} min before each activity starts.',
  'Completa el {0} % de las actividades de un día para sumar a tu racha.': 'Complete {0} % of a day’s activities to add to your streak.',
  'Todos los días cuentan.': 'Every day counts.', 'Los demás días no suman ni rompen tu racha.': 'The other days neither add to nor break your streak.',
  'Aparece un botón en Estadísticas para enviar un texto con tus totales por categoría y tu racha. Nunca incluye los títulos de tus actividades.': 'A button appears in Statistics to send a text with your totals per category and your streak. It never includes your activity titles.',
  'Desactivado. Si lo activas, podrás enviar un resumen de tu semana desde Estadísticas.': 'Off. If you turn it on, you can send a summary of your week from Statistics.',
  'Instálala para abrirla como una app, a pantalla completa y sin conexión.': 'Install it to open it like an app, full screen and offline.',
  'En Safari pulsa Compartir y después "Añadir a pantalla de inicio".': 'In Safari tap Share and then “Add to Home Screen”.',
  'Al menos un día tiene que contar.': 'At least one day has to count.', 'Copia descargada': 'Backup downloaded', 'Copia lista para guardar': 'Backup ready to save',
  'No se pudo exportar la copia.': 'The backup could not be exported.',
  'Se restaurarán {0} y se sobrescribirán los que ya existan. ¿Continuar?': '{0} will be restored and any that already exist will be overwritten. Continue?',
  'Copia restaurada': 'Backup restored', 'No se pudo importar el archivo.': 'The file could not be imported.',
  'No se pudo conectar con la nube. Comprueba tu conexión e inténtalo de nuevo.': 'Could not connect to the cloud. Check your connection and try again.',
  'Inicia sesión para ver y guardar tu horario.': 'Sign in to see and save your schedule.',
  'Abierta como archivo, no se puede iniciar sesión. Ábrela desde una dirección https:// o http://localhost.': 'Opened as a file, signing in is not possible. Open it from an https:// or http://localhost address.',
  'Sesión iniciada como {0}. Tus cambios se sincronizan solos.': 'Signed in as {0}. Your changes sync automatically.',
  'Sin conexión con la nube. Tus cambios se guardan en este dispositivo y se subirán al volver la conexión.': 'No connection to the cloud. Your changes are saved on this device and will upload when the connection returns.',
  'Escribe tu correo y tu contraseña.': 'Enter your email and password.', 'Cuenta creada': 'Account created', 'Sesión iniciada': 'Signed in',
  'Escribe tu correo y vuelve a pulsar.': 'Enter your email and press again.',
  'Si el correo existe, te enviaremos un enlace para cambiar la contraseña.': 'If the email exists, we will send you a link to change the password.',
  'Escribe tu contraseña para confirmar.': 'Enter your password to confirm.', 'Cuenta eliminada. Se han borrado tus datos.': 'Account deleted. Your data has been erased.',
  'No se pudo eliminar la cuenta.': 'The account could not be deleted.',
  'La nube rechazó el cambio. Revisa las reglas de Firestore.': 'The cloud rejected the change. Check the Firestore rules.',
  'No se pudo sincronizar con la nube.': 'Could not sync with the cloud.', '¿Compartir estadísticas de uso anónimas?': 'Share anonymous usage statistics?',
  'En {0} min: {1}': 'In {0} min: {1}', 'Ahora: {0}': 'Now: {0}', '¡Toca {0}!': 'Time for {0}!',
  'Copia de Mi horario': 'Mi horario backup', 'Guardar copia': 'Save backup', 'No se pudo leer el archivo.': 'The file could not be read.',
  'Mi semana': 'My week', 'Horario DAM de ejemplo': 'Sample DAM schedule', 'Usar el horario DAM de ejemplo': 'Use the sample DAM schedule', 'Al empezar': 'At start', '{0} min antes': '{0} min before', 'pizarra': 'slate', 'cobre': 'copper', 'violeta': 'violet', 'menta': 'mint', 'gris': 'grey', 'turquesa': 'turquoise', 'rojo': 'red', 'rosa': 'pink', 'mostaza': 'mustard', 'azul': 'blue', 'verde': 'green', 'naranja': 'orange', 'menos de 1 min': 'less than 1 min', 'Mi semana ({0})': 'My week ({0})',

  /* ── Reglas y errores (state-manager.js, firebase-service.js) ── */
  'Escribe un nombre para la actividad.': 'Enter a name for the activity.', 'Elige la hora de inicio y de fin.': 'Choose the start and end time.',
  'La hora de fin debe ser posterior al inicio.': 'The end time must be after the start.', 'El archivo no es un JSON válido.': 'The file is not valid JSON.',
  'Este archivo no es una copia de Mi horario.': 'This file is not a Mi horario backup.', 'La copia no contiene datos válidos.': 'The backup contains no valid data.',
  'Fecha no válida: {0}': 'Invalid date: {0}', 'Máximo {0} actividades por día.': 'Maximum {0} activities per day.',
  'La actividad no es válida.': 'The activity is not valid.', 'La actividad ya no existe.': 'That activity no longer exists.',
  'Elige al menos un día.': 'Choose at least one day.', 'No se copió nada: esas horas ya están ocupadas.': 'Nothing was copied: those times are already taken.',
  'Máximo {0} repeticiones. Quita alguna.': 'Maximum {0} repeats. Remove one.', 'La repetición no es válida.': 'The repeat is not valid.',
  'Esa repetición ya terminó.': 'That repeat has already ended.', 'Este día no tiene actividades que guardar.': 'This day has no activities to save.',
  'Escribe un nombre para la plantilla.': 'Enter a name for the template.', 'Máximo {0} plantillas. Elimina alguna.': 'Maximum {0} templates. Delete one.',
  'Ya tienes una plantilla con ese nombre.': 'You already have a template with that name.', 'No se pudo crear la plantilla.': 'The template could not be created.',
  'Añadir «{0}»': 'Add “{0}”', 'Plantilla desconocida.': 'Unknown template.', 'Esas horas ya están ocupadas por otras actividades.': 'Those times are already taken by other activities.',
  'Solo puedes cambiar hoy o días que aún no han llegado.': 'You can only change today or days that have not arrived yet.',
  'Ese día queda demasiado lejos.': 'That day is too far away.', 'Tienes demasiados días de descanso marcados.': 'You have too many rest days marked.',
  'Correo o contraseña incorrectos.': 'Incorrect email or password.', 'El correo no es válido.': 'The email is not valid.', 'Escribe tu contraseña.': 'Enter your password.',
  'Ese correo ya tiene cuenta. Pulsa Entrar.': 'That email already has an account. Press Sign in.', 'La contraseña debe tener al menos 6 caracteres.': 'The password must be at least 6 characters.',
  'Sin conexión. Inténtalo de nuevo.': 'No connection. Try again.', 'Demasiados intentos. Espera un momento.': 'Too many attempts. Wait a moment.',
  'Activa "Correo electrónico/contraseña" en Firebase → Authentication → Método de acceso.': 'Enable “Email/Password” in Firebase → Authentication → Sign-in method.',
  'Authentication no está iniciado: en la consola de Firebase abre Authentication y pulsa "Comenzar".': 'Authentication is not set up: in the Firebase console open Authentication and press “Get started”.',
  'Añade este dominio en Authentication → Configuración → Dominios autorizados.': 'Add this domain in Authentication → Settings → Authorized domains.',
  'El registro de cuentas nuevas está desactivado en Firebase → Authentication → Configuración.': 'New account sign-up is disabled in Firebase → Authentication → Settings.',
  'La clave de API de Firebase no es válida. Revisa la configuración.': 'The Firebase API key is not valid. Check the configuration.',
  'Por seguridad, cierra sesión, vuelve a entrar e inténtalo otra vez.': 'For security, sign out, sign back in and try again.',
  'Sin conexión. Conéctate a internet e inténtalo de nuevo.': 'No connection. Connect to the internet and try again.',
  'La nube rechazó la operación. Revisa que las reglas de Firestore estén publicadas.': 'The cloud rejected the operation. Check that the Firestore rules are published.',
  'Error interno de Firebase. Inténtalo de nuevo en un momento.': 'Internal Firebase error. Try again in a moment.',
  'No se pudo completar la operación ({0}).': 'The operation could not be completed ({0}).', 'Sin conexión con la nube.': 'No connection to the cloud.',
  'No hay una sesión iniciada.': 'You are not signed in.', 'Contraseña incorrecta.': 'Incorrect password.',
  'Etiqueta': 'Tag', 'Crear': 'Create', 'Etiquetas': 'Tags',
  'Agrupa actividades por proyecto o tema y mira cuánto tiempo les dedicas.': 'Group activities by project or topic and see how much time you spend on them.',
  'Exportar al calendario': 'Export to calendar',
  'Crea un archivo .ics para Calendario de iPhone o Google Calendar.': 'Creates an .ics file for iPhone Calendar or Google Calendar.',
  'Úsalas para agrupar actividades por proyecto o tema (por ejemplo «TFG» o «Carnet de conducir»). Se eligen al crear o editar una actividad, y en Estadísticas ves el tiempo de cada una.': 'Use them to group activities by project or topic (for example "Thesis" or "Driving licence"). You pick them when creating or editing an activity, and in Stats you see the time for each one.',
  'Crea un archivo .ics con tus actividades, que puedes abrir en el Calendario de iPhone, Google Calendar u Outlook. Es una copia: si luego cambias algo aquí, vuelve a exportar.': 'Creates an .ics file with your activities that you can open in iPhone Calendar, Google Calendar or Outlook. It is a copy: if you change something here later, export again.',
  'Qué días': 'Which days', 'Aviso del calendario': 'Calendar alert', 'Nueva etiqueta': 'New tag', 'Qué días exportar': 'Which days to export',
  'Se exportarán {0} en {1}.': '{0} will be exported over {1}.',
  'No hay actividades en ese periodo.': 'There are no activities in that period.', 'Sin aviso': 'No alert',
  'Archivo descargado. Ábrelo para añadirlo al calendario.': 'File downloaded. Open it to add it to your calendar.',
  'Archivo listo para el calendario': 'File ready for the calendar', 'No se pudo crear el archivo.': 'The file could not be created.',
  'Sin etiqueta': 'No tag', 'Nombre de la etiqueta': 'Tag name', 'Aún no tienes etiquetas.': 'You have no tags yet.', 'Por etiqueta': 'By tag',
  'Etiqueta eliminada': 'Tag deleted',
  'Avisos con la app cerrada': 'Alerts with the app closed',
  'Inicia sesión para usar los avisos con la app cerrada.': 'Sign in to use alerts with the app closed.',
  'Activado. Te llegan los avisos aunque la app esté cerrada. Se guarda en la nube la hora y el título de tus próximas actividades.': 'On. You get alerts even when the app is closed. The time and title of your upcoming activities are stored in the cloud.',
  'Desactivado. Si lo activas, los avisos llegan aunque la app esté cerrada (en iPhone, con la app añadida a la pantalla de inicio).': 'Off. If you turn it on, alerts arrive even when the app is closed (on iPhone, with the app added to the Home Screen).',
  'Permiso de notificaciones denegado.': 'Notification permission denied.',
  'Avisos con la app cerrada activados.': 'Alerts with the app closed turned on.',
  'No se pudo activar. Comprueba la conexión e inténtalo de nuevo.': 'Could not turn it on. Check your connection and try again.',
  'Resumen cada semana': 'Weekly summary', 'Tu semana pasada': 'Your last week', 'Racha: {0} días 🔥': 'Streak: {0} days 🔥',
  'Cada semana, al abrir la app, verás un resumen de la semana anterior. Solo se muestra aquí: no se envía a ningún sitio.': 'Each week, when you open the app, you will see a summary of the previous week. It is only shown here: it is not sent anywhere.',
  'Desactivado. Si lo activas, al abrir la app en una semana nueva verás cómo fue la anterior.': 'Off. If you turn it on, when you open the app in a new week you will see how the previous one went.',
  'Escribe un nombre para la etiqueta.': 'Enter a name for the tag.', 'Ya tienes una etiqueta con ese nombre.': 'You already have a tag with that name.',
  'La etiqueta ya no existe.': 'That tag no longer exists.', 'Máximo {0} etiquetas. Elimina alguna.': 'Maximum {0} tags. Delete one.'
});

/** Palabras sueltas que cambian con el número: [singular, plural]. */
export const EN_PLURAL = Object.freeze({
  'actividad': ['activity', 'activities'], 'actividad añadida': ['activity added', 'activities added'],
  'actividad más': ['more activity', 'more activities'], 'día': ['day', 'days'], 'omitida': ['skipped', 'skipped'],
  'día con actividades': ['day with activities', 'days with activities'], 'semana': ['week', 'weeks']
});
